;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : ACFDB848C0F2630E4EC729F66D5AE1CD09D6FE4E9C81EA5AE6FEEAB06E051A99
; Input MD5    : 7C2477DE6E23BFC12EA7130B7E29A0FA
; Input CRC32  : 5AB60128
; Compiler     : GNU C++

; File Name   : /home/nhanpham/crackmes/Sh4ll4/a.out
; Format      : ELF64 for x86-64 (Shared object)
; Interpreter '/lib64/ld-linux-x86-64.so.2'
; Needed Library 'libc.so.6'
;
; Source File : 'crtstuff.c'
; Source File : 'main.c'
; Source File : 'crtstuff.c'

.686p
.mmx
.model flat
.intel_syntax noprefix


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
dword_0 dd 464C457Fh    ; File format: \x7FELF
db 2                    ; File class: 64-bit
db 1                    ; Data encoding: little-endian
db 1                    ; File version
db 0                    ; OS/ABI: UNIX System V ABI
db 0                    ; ABI Version
db 7 dup(0)             ; Padding
dw 3                    ; File type: Shared object
dw 3Eh                  ; Machine: x86-64
dd 1                    ; File version
dq offset _start        ; Entry point
dq 40h                  ; PHT file offset
dq 2B68h                ; SHT file offset
dd 0                    ; Processor-specific flags
dw 40h                  ; ELF header size
dw 38h                  ; PHT entry size
dw 9                    ; Number of entries in PHT
dw 40h                  ; SHT entry size
dw 1Fh                  ; Number of entries in SHT
dw 1Eh                  ; SHT entry index for string table
; ELF64 Program Header
; PHT Entry 0
dword_40 dd 6           ; Type: PHDR
dd 5                    ; Flags
dq 40h                  ; File offset
dq offset dword_40      ; Virtual address
dq 40h                  ; Physical address
dq 1F8h                 ; Size in file image
dq 1F8h                 ; Size in memory image
dq 8                    ; Alignment
; PHT Entry 1
dd 3                    ; Type: INTERP
dd 4                    ; Flags
dq 238h                 ; File offset
dq offset aLib64LdLinuxX8 ; Virtual address
dq 238h                 ; Physical address
dq 1Ch                  ; Size in file image
dq 1Ch                  ; Size in memory image
dq 1                    ; Alignment
; PHT Entry 2
dd 1                    ; Type: LOAD
dd 5                    ; Flags
dq 0                    ; File offset
dq 0                    ; Virtual address
dq 0                    ; Physical address
dq 0F1Ch                ; Size in file image
dq 0F1Ch                ; Size in memory image
dq 200000h              ; Alignment
; PHT Entry 3
dd 1                    ; Type: LOAD
dd 6                    ; Flags
dq 1DD8h                ; File offset
dq offset __frame_dummy_init_array_entry ; Virtual address
dq 201DD8h              ; Physical address
dq 278h                 ; Size in file image
dq 288h                 ; Size in memory image
dq 200000h              ; Alignment
; PHT Entry 4
dd 2                    ; Type: DYNAMIC
dd 6                    ; Flags
dq 1DF0h                ; File offset
dq offset _DYNAMIC      ; Virtual address
dq 201DF0h              ; Physical address
dq 1E0h                 ; Size in file image
dq 1E0h                 ; Size in memory image
dq 8                    ; Alignment
; PHT Entry 5
dd 4                    ; Type: NOTE
dd 4                    ; Flags
dq 254h                 ; File offset
dq offset dword_254     ; Virtual address
dq 254h                 ; Physical address
dq 44h                  ; Size in file image
dq 44h                  ; Size in memory image
dq 4                    ; Alignment
; PHT Entry 6
dd 6474E550h            ; Type: EH_FRAME
dd 4                    ; Flags
dq 0D54h                ; File offset
dq offset __GNU_EH_FRAME_HDR ; Virtual address
dq 0D54h                ; Physical address
dq 54h                  ; Size in file image
dq 54h                  ; Size in memory image
dq 4                    ; Alignment
; PHT Entry 7
dd 6474E551h            ; Type: STACK
dd 6                    ; Flags
dq 0                    ; File offset
dq 0                    ; Virtual address
dq 0                    ; Physical address
dq 0                    ; Size in file image
dq 0                    ; Size in memory image
dq 10h                  ; Alignment
; PHT Entry 8
dd 6474E552h            ; Type: RO-AFTER
dd 4                    ; Flags
dq 1DD8h                ; File offset
dq offset __frame_dummy_init_array_entry ; Virtual address
dq 201DD8h              ; Physical address
dq 228h                 ; Size in file image
dq 228h                 ; Size in memory image
dq 1                    ; Alignment
aLib64LdLinuxX8 db '/lib64/ld-linux-x86-64.so.2',0
; ELF Note Entry
dword_254 dd 4          ; Name Size
dd 10h                  ; Desc Size
dd 1                    ; Type: NT_GNU_ABI_TAG
aGnu db 'GNU',0         ; Name
dd 0, 2, 6, 20h         ; ABI: Linux 2.6.32
; ELF Note Entry
dd 4                    ; Name Size
dd 14h                  ; Desc Size
dd 3                    ; Type: NT_GNU_BUILD_ID
aGnu_0 db 'GNU',0       ; Name
db 55h, 2Ah, 52h, 0BBh, 0C8h, 0F5h, 8Fh ; Desc
db 0F3h, 73h, 6Eh, 0B8h, 0DFh, 51h, 56h
db 0ABh, 0BFh, 29h, 49h, 0F1h, 40h
; ELF GNU Hash Table
elf_gnu_hash_nbuckets dd 2
elf_gnu_hash_symbias dd 0Ch
elf_gnu_hash_bitmask_nwords dd 1
elf_gnu_hash_shift dd 6
elf_gnu_hash_indexes dq 8000200000h
elf_gnu_hash_bucket dd 0, 0Ch
elf_gnu_hash_chain dd 10615567h, 0
; ELF Symbol Table
Elf64_Sym <0>
Elf64_Sym <offset aItmDeregistert - offset byte_3F8,\ ; "_ITM_deregisterTMCloneTable"
           20h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aPuts - offset byte_3F8,\ ; "puts"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aStrlen - offset byte_3F8,\ ; "strlen"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aLibcStartMain - offset byte_3F8,\ ; "__libc_start_main"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aFgets - offset byte_3F8,\ ; "fgets"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aStrcmp - offset byte_3F8,\ ; "strcmp"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aGmonStart - offset byte_3F8,\ ; "__gmon_start__"
           20h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aPtrace - offset byte_3F8,\ ; "ptrace"
           12h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aJvRegisterclas - offset byte_3F8,\ ; "_Jv_RegisterClasses"
           20h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aItmRegistertmc - offset byte_3F8,\ ; "_ITM_registerTMCloneTable"
           20h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aCxaFinalize - offset byte_3F8,\ ; "__cxa_finalize"
           22h, 0, 0, offset dword_0, 0>
Elf64_Sym <offset aStdin - offset byte_3F8,\ ; "stdin"
           11h, 0, 1Ah, \
           offset __bss_start, 8>
; ELF String Table
byte_3F8 db 0
aLibcSo6 db 'libc.so.6',0
aPuts db 'puts',0
aStdin db 'stdin',0
aFgets db 'fgets',0
aStrlen db 'strlen',0
aPtrace db 'ptrace',0
aCxaFinalize db '__cxa_finalize',0
aStrcmp db 'strcmp',0
aLibcStartMain db '__libc_start_main',0
aItmDeregistert db '_ITM_deregisterTMCloneTable',0
aGmonStart db '__gmon_start__',0
aJvRegisterclas db '_Jv_RegisterClasses',0
aItmRegistertmc db '_ITM_registerTMCloneTable',0
aGlibc225 db 'GLIBC_2.2.5',0
align 10h
; ELF GNU Symbol Version Table
dw 0
dw 0                    ; local  symbol: _ITM_deregisterTMCloneTable
dw 2                    ; puts@@GLIBC_2.2.5
dw 2                    ; strlen@@GLIBC_2.2.5
dw 2                    ; __libc_start_main@@GLIBC_2.2.5
dw 2                    ; fgets@@GLIBC_2.2.5
dw 2                    ; strcmp@@GLIBC_2.2.5
dw 0                    ; local  symbol: __gmon_start__
dw 2                    ; ptrace@@GLIBC_2.2.5
dw 0                    ; local  symbol: _Jv_RegisterClasses
dw 0                    ; local  symbol: _ITM_registerTMCloneTable
dw 2                    ; __cxa_finalize@@GLIBC_2.2.5
dw 2                    ; stdin@@GLIBC_2.2.5
dw 0
dw 0
dw 0
; ELF GNU Symbol Version Requirements
Elf64_Verneed <1, 1, \  ; "libc.so.6"
               offset aLibcSo6 - offset byte_3F8,\
               10h, 0>
Elf64_Vernaux <9691A75h, 0, 2, \ ; "GLIBC_2.2.5"
               offset aGlibc225 - offset byte_3F8,\
               0>
; ELF RELA Relocation Table
Elf64_Rela <201DD8h, 8, 7E0h> ; R_X86_64_RELATIVE +7E0h
Elf64_Rela <201DE0h, 8, 7A0h> ; R_X86_64_RELATIVE +7A0h
Elf64_Rela <202048h, 8, 202048h> ; R_X86_64_RELATIVE +202048h
Elf64_Rela <201FD0h, 100000006h, 0> ; R_X86_64_GLOB_DAT _ITM_deregisterTMCloneTable
Elf64_Rela <201FD8h, 400000006h, 0> ; R_X86_64_GLOB_DAT __libc_start_main
Elf64_Rela <201FE0h, 700000006h, 0> ; R_X86_64_GLOB_DAT __gmon_start__
Elf64_Rela <201FE8h, 900000006h, 0> ; R_X86_64_GLOB_DAT _Jv_RegisterClasses
Elf64_Rela <201FF0h, 0A00000006h, 0> ; R_X86_64_GLOB_DAT _ITM_registerTMCloneTable
Elf64_Rela <201FF8h, 0B00000006h, 0> ; R_X86_64_GLOB_DAT __cxa_finalize
Elf64_Rela <202050h, 0C00000005h, 0> ; R_X86_64_COPY stdin
; ELF JMPREL Relocation Table
Elf64_Rela <202018h, 200000007h, 0> ; R_X86_64_JUMP_SLOT puts
Elf64_Rela <202020h, 300000007h, 0> ; R_X86_64_JUMP_SLOT strlen
Elf64_Rela <202028h, 500000007h, 0> ; R_X86_64_JUMP_SLOT fgets
Elf64_Rela <202030h, 600000007h, 0> ; R_X86_64_JUMP_SLOT strcmp
Elf64_Rela <202038h, 800000007h, 0> ; R_X86_64_JUMP_SLOT ptrace
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_init segment dword public 'CODE' use64
assume cs:_init
;org 658h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _init_proc
_init_proc proc near
sub     rsp, 8          ; _init
mov     rax, cs:__gmon_start___ptr
test    rax, rax
jz      short loc_66A
call    rax ; __gmon_start__

loc_66A:
add     rsp, 8
retn
_init_proc endp

_init ends


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
;org 66Fh
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
align 10h
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_plt segment para public 'CODE' use64
assume cs:_plt
;org 670h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



sub_670 proc near
; __unwind {
push    cs:qword_202008
jmp     cs:qword_202010
sub_670 endp

align 20h
; [00000006 BYTES: COLLAPSED FUNCTION _puts. PRESS CTRL-NUMPAD+ TO EXPAND]
push    0
jmp     sub_670
; [00000006 BYTES: COLLAPSED FUNCTION _strlen. PRESS CTRL-NUMPAD+ TO EXPAND]
push    1
jmp     sub_670
; [00000006 BYTES: COLLAPSED FUNCTION _fgets. PRESS CTRL-NUMPAD+ TO EXPAND]
push    2
jmp     sub_670
; [00000006 BYTES: COLLAPSED FUNCTION _strcmp. PRESS CTRL-NUMPAD+ TO EXPAND]
push    3
jmp     sub_670
; [00000006 BYTES: COLLAPSED FUNCTION _ptrace. PRESS CTRL-NUMPAD+ TO EXPAND]
push    4
jmp     sub_670
; } // starts at 670
_plt ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_plt_got segment qword public 'CODE' use64
assume cs:_plt_got
;org 6D0h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
; [00000006 BYTES: COLLAPSED FUNCTION __cxa_finalize. PRESS CTRL-NUMPAD+ TO EXPAND]
align 8
; } // starts at 6D0
_plt_got ends


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
;org 6D8h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
align 20h
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 6E0h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing


; Attributes: noreturn fuzzy-sp

public _start
_start proc near
; __unwind {
xor     ebp, ebp
mov     r9, rdx         ; rtld_fini
pop     rsi             ; argc
mov     rdx, rsp        ; ubp_av
and     rsp, 0FFFFFFFFFFFFFFF0h
push    rax
push    rsp             ; stack_end
lea     r8, __libc_csu_fini ; fini
lea     rcx, __libc_csu_init ; init
lea     rdi, main       ; main
call    cs:__libc_start_main_ptr
hlt
; } // starts at 6E0
_start endp

align 10h


; Attributes: bp-based frame

deregister_tm_clones proc near
lea     rdi, __bss_start
lea     rax, __bss_start+7
push    rbp
sub     rax, rdi
mov     rbp, rsp
cmp     rax, 0Eh
jbe     short loc_740
mov     rax, cs:_ITM_deregisterTMCloneTable_ptr
test    rax, rax
jz      short loc_740
pop     rbp
jmp     rax
align 20h

loc_740:
pop     rbp
retn
deregister_tm_clones endp

align 10h


; Attributes: bp-based frame

register_tm_clones proc near
lea     rdi, __bss_start
lea     rsi, __bss_start
push    rbp
sub     rsi, rdi
mov     rbp, rsp
sar     rsi, 3
mov     rax, rsi
shr     rax, 3Fh
add     rsi, rax
sar     rsi, 1
jz      short loc_790
mov     rax, cs:_ITM_registerTMCloneTable_ptr
test    rax, rax
jz      short loc_790
pop     rbp
jmp     rax
align 10h

loc_790:
pop     rbp
retn
register_tm_clones endp

align 20h



__do_global_dtors_aux proc near
cmp     cs:completed_6972, 0
jnz     short locret_7D0
cmp     cs:__cxa_finalize_ptr, 0
push    rbp
mov     rbp, rsp
jz      short loc_7C3
mov     rdi, cs:__dso_handle ; void *
call    __cxa_finalize

loc_7C3:
call    deregister_tm_clones
pop     rbp
mov     cs:completed_6972, 1

locret_7D0:
rep retn
__do_global_dtors_aux endp

align 20h



frame_dummy proc near
lea     rdi, __JCR_LIST__
cmp     qword ptr [rdi], 0
jnz     short loc_7F8

loc_7ED:
jmp     register_tm_clones
align 8

loc_7F8:
mov     rax, cs:_Jv_RegisterClasses_ptr
test    rax, rax
jz      short loc_7ED
push    rbp
mov     rbp, rsp
call    rax ; _Jv_RegisterClasses
pop     rbp
jmp     register_tm_clones
frame_dummy endp



; Attributes: bp-based frame

public youwillneveeeeerwindude
youwillneveeeeerwindude proc near

var_4= dword ptr -4

; __unwind {
push    rbp
mov     rbp, rsp
sub     rsp, 10h
mov     [rbp+var_4], edi
mov     ecx, 0
mov     edx, 1
mov     esi, 0
mov     edi, 0          ; request
mov     eax, 0
call    _ptrace
test    rax, rax
jz      short loc_84B
cmp     [rbp+var_4], 0FFFFFFFFh
jz      short loc_84B
mov     eax, 1B39h
jmp     short locret_850

loc_84B:
mov     eax, 5

locret_850:
leave
retn
; } // starts at 810
youwillneveeeeerwindude endp



; Attributes: bp-based frame

public function
function proc near
; __unwind {
push    rbp
mov     rbp, rsp
mov     ecx, 0
mov     edx, 1
mov     esi, 0
mov     edi, 0          ; request
mov     eax, 0
call    _ptrace
test    rax, rax
jz      short loc_882
lea     rax, a142x142x121x14 ; "142x142x121x1424421"
jmp     short loc_889

loc_882:
lea     rax, a142x142x121x14_0 ; "142x142x121x1424421x"

loc_889:
pop     rbp
retn
; } // starts at 852
function endp



; Attributes: bp-based frame

public debugMe
debugMe proc near

var_110= qword ptr -110h
var_108= qword ptr -108h
var_100= qword ptr -100h
var_F8= qword ptr -0F8h
var_F0= qword ptr -0F0h
var_E8= qword ptr -0E8h
var_E0= qword ptr -0E0h
var_D8= qword ptr -0D8h
var_D0= qword ptr -0D0h
var_C8= dword ptr -0C8h
var_C4= word ptr -0C4h
var_C0= qword ptr -0C0h
var_B8= qword ptr -0B8h
var_B0= qword ptr -0B0h
var_A8= dword ptr -0A8h
var_A4= word ptr -0A4h
var_A0= qword ptr -0A0h
var_98= qword ptr -98h
var_90= qword ptr -90h
var_88= dword ptr -88h
var_84= word ptr -84h
var_80= qword ptr -80h
var_78= qword ptr -78h
var_70= qword ptr -70h
var_68= dword ptr -68h
var_64= word ptr -64h
var_60= dword ptr -60h
var_5C= dword ptr -5Ch
s1= qword ptr -58h
var_50= qword ptr -50h
s2= qword ptr -48h
var_40= qword ptr -40h
s= qword ptr -38h
var_2C= dword ptr -2Ch
var_25= byte ptr -25h
var_24= dword ptr -24h

; __unwind {
push    rbp
mov     rbp, rsp
push    r14
push    r13
push    r12
push    rbx
sub     rsp, 0F0h
mov     rax, rsp
mov     r12, rax
mov     rax, 317A39683461617Ah
mov     [rbp+var_80], rax
mov     rax, 3167356167386167h
mov     [rbp+var_78], rax
mov     [rbp+var_70], 347A3868h
mov     [rbp+var_68], 0
mov     [rbp+var_64], 0
mov     rax, 7A31346861383165h
mov     [rbp+var_A0], rax
mov     rax, 7A35306861316838h
mov     [rbp+var_98], rax
mov     [rbp+var_90], 67683961h
mov     [rbp+var_88], 0
mov     [rbp+var_84], 0
mov     rax, 67346138687A327Ah
mov     [rbp+var_C0], rax
mov     rax, 68397A3168613439h
mov     [rbp+var_B8], rax
mov     [rbp+var_B0], 61613167h
mov     [rbp+var_A8], 0
mov     [rbp+var_A4], 0
mov     rax, 4868396134684847h
mov     [rbp+var_E0], rax
mov     rax, 317A386B514A5A52h
mov     [rbp+var_D8], rax
mov     [rbp+var_D0], 7A323168h
mov     [rbp+var_C8], 0
mov     [rbp+var_C4], 0
mov     eax, 0
call    function
mov     [rbp+s], rax
mov     rax, [rbp+s]
mov     rdi, rax        ; s
call    _strlen
lea     rcx, [rax+1]
mov     rax, rcx
sub     rax, 1
mov     [rbp+var_40], rax
mov     [rbp+var_F0], rcx
mov     [rbp+var_E8], 0
mov     [rbp+var_100], rcx
mov     [rbp+var_F8], 0
mov     eax, 10h
sub     rax, 1
add     rax, rcx
mov     esi, 10h
mov     edx, 0
div     rsi
imul    rax, 10h
sub     rsp, rax
mov     rax, rsp
add     rax, 0
mov     [rbp+s2], rax
mov     rdx, cs:__bss_start ; stream
mov     rax, [rbp+s2]
mov     esi, ecx        ; n
mov     rdi, rax        ; s
call    _fgets
mov     rax, [rbp+s]
mov     rdi, rax        ; s
call    _strlen
lea     rcx, [rax+1]
mov     rax, rcx
sub     rax, 1
mov     [rbp+var_50], rax
mov     [rbp+var_110], rcx
mov     [rbp+var_108], 0
mov     r13, rcx
mov     r14d, 0
mov     eax, 10h
sub     rax, 1
add     rax, rcx
mov     ebx, 10h
mov     edx, 0
div     rbx
imul    rax, 10h
sub     rsp, rax
mov     rax, rsp
add     rax, 0
mov     [rbp+s1], rax
lea     rdx, [rcx-1]
mov     rax, [rbp+s1]
mov     byte ptr [rax+rdx], 0
mov     [rbp+var_24], 0
jmp     loc_BAE

loc_A9A:
mov     eax, [rbp+var_24]
movsxd  rdx, eax
mov     rax, [rbp+s]
add     rax, rdx
movzx   eax, byte ptr [rax]
movsx   eax, al
sub     eax, 30h ; '0'
mov     [rbp+var_5C], eax
mov     [rbp+var_25], 0
mov     eax, [rbp+var_5C]
cmp     eax, 2
jz      short loc_AE9
cmp     eax, 2
jg      short loc_ACB
cmp     eax, 1
jz      short loc_AD7
jmp     short loc_B1C

loc_ACB:
cmp     eax, 3
jz      short loc_AF8
cmp     eax, 4
jz      short loc_B0A
jmp     short loc_B1C

loc_AD7:
mov     eax, [rbp+var_24]
cdqe
movzx   eax, byte ptr [rbp+rax+var_A0]
mov     [rbp+var_25], al
jmp     short loc_B21

loc_AE9:
mov     eax, [rbp+var_24]
cdqe
movzx   eax, byte ptr [rbp+rax+var_80]
mov     [rbp+var_25], al
jmp     short loc_B21

loc_AF8:
mov     eax, [rbp+var_24]
cdqe
movzx   eax, byte ptr [rbp+rax+var_C0]
mov     [rbp+var_25], al
jmp     short loc_B21

loc_B0A:
mov     eax, [rbp+var_24]
cdqe
movzx   eax, byte ptr [rbp+rax+var_E0]
mov     [rbp+var_25], al
jmp     short loc_B21

loc_B1C:
mov     [rbp+var_25], 53h ; 'S'
nop

loc_B21:
mov     [rbp+var_2C], 0
mov     rax, [rbp+s]
mov     rdi, rax        ; s
call    _strlen
lea     rdx, [rax-1]
mov     rax, [rbp+s]
add     rax, rdx
movzx   eax, byte ptr [rax]
cmp     al, 78h ; 'x'
jz      short loc_B4F
mov     [rbp+var_2C], 0FFFFFFFFh
jmp     short loc_B74

loc_B4F:
mov     rax, [rbp+s]
mov     rdi, rax        ; s
call    _strlen
lea     rdx, [rax-1]
mov     rax, [rbp+s]
add     rax, rdx
movzx   eax, byte ptr [rax]
cmp     al, 31h ; '1'
jnz     short loc_B74
mov     [rbp+var_2C], 0FFFFFFFFh

loc_B74:
mov     eax, [rbp+var_2C]
mov     edi, eax
call    youwillneveeeeerwindude
mov     [rbp+var_60], eax
cmp     [rbp+var_60], 5
jz      short loc_B8D
cmp     [rbp+var_60], 0
jnz     short loc_B9A

loc_B8D:
mov     rdx, [rbp+s2]
mov     eax, [rbp+var_24]
cdqe
mov     byte ptr [rdx+rax], 3Fh ; '?'

loc_B9A:
mov     rdx, [rbp+s1]
mov     eax, [rbp+var_24]
cdqe
movzx   ecx, [rbp+var_25]
mov     [rdx+rax], cl
add     [rbp+var_24], 1

loc_BAE:
mov     eax, [rbp+var_24]
movsxd  rbx, eax
mov     rax, [rbp+s]
mov     rdi, rax        ; s
call    _strlen
cmp     rbx, rax
jb      loc_A9A
mov     rdx, [rbp+s2]
mov     rax, [rbp+s1]
mov     rsi, rdx        ; s2
mov     rdi, rax        ; s1
call    _strcmp
test    eax, eax
jnz     short loc_BEE
lea     rdi, s          ; "YEAAAAAAAAAH YOU ARE GOOD MAN!"
call    _puts
jmp     short loc_BFA

loc_BEE:
lea     rdi, aBadPasswordYou ; "Bad password, you can buy the product b"...
call    _puts

loc_BFA:
mov     rsp, r12
nop
lea     rsp, [rbp-20h]
pop     rbx
pop     r12
pop     r13
pop     r14
pop     rbp
retn
; } // starts at 88B
debugMe endp



; Attributes: bp-based frame

; int __fastcall main(int argc, const char **argv, const char **envp)
public main
main proc near
; __unwind {
push    rbp
mov     rbp, rsp
mov     eax, 0
call    debugMe
mov     eax, 0
pop     rbp
retn
; } // starts at C0B
main endp




; void _libc_csu_init(void)
public __libc_csu_init
__libc_csu_init proc near
; __unwind {
push    r15
push    r14
mov     r15d, edi
push    r13
push    r12
lea     r12, __frame_dummy_init_array_entry
push    rbp
lea     rbp, __do_global_dtors_aux_fini_array_entry
push    rbx
mov     r14, rsi
mov     r13, rdx
sub     rbp, r12
sub     rsp, 8
sar     rbp, 3
call    _init_proc
test    rbp, rbp
jz      short loc_C76
xor     ebx, ebx
nop     dword ptr [rax+rax+00000000h]

loc_C60:
mov     rdx, r13
mov     rsi, r14
mov     edi, r15d
call    ds:(__frame_dummy_init_array_entry - 201DD8h)[r12+rbx*8]
add     rbx, 1
cmp     rbp, rbx
jnz     short loc_C60

loc_C76:
add     rsp, 8
pop     rbx
pop     rbp
pop     r12
pop     r13
pop     r14
pop     r15
retn
; } // starts at C20
__libc_csu_init endp

align 10h



; void _libc_csu_fini(void)
public __libc_csu_fini
__libc_csu_fini proc near
; __unwind {
rep retn
; } // starts at C90
__libc_csu_fini endp

_text ends


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
;org 0C92h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
align 4
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_fini segment dword public 'CODE' use64
assume cs:_fini
;org 0C94h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _term_proc
_term_proc proc near
sub     rsp, 8          ; _fini
add     rsp, 8
retn
_term_proc endp

_fini ends


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
;org 0C9Dh
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
align 20h
LOAD ends


; Segment type: Pure data
; Segment permissions: Read
_rodata segment qword public 'CONST' use64
assume cs:_rodata
;org 0CA0h
public _IO_stdin_used
_IO_stdin_used db    1
db    0
db    2
db    0
db    0
db    0
db    0
db    0
a142x142x121x14 db '142x142x121x1424421',0
a142x142x121x14_0 db '142x142x121x1424421x',0
align 8
; const char s[]
s db 'YEAAAAAAAAAH YOU ARE GOOD MAN!',0
align 8
; const char aBadPasswordYou[]
aBadPasswordYou db 'Bad password, you can buy the produ'
db 'ct by sending $10: 1Fn3N79g2soMWQES'
db '2ZWVUu59Y4xKf3hWKh',0
_rodata ends


; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD segment byte public 'CODE' use64
assume cs:LOAD
;org 0D51h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
align 4
LOAD ends


; Segment type: Pure data
; Segment permissions: Read
_eh_frame_hdr segment dword public 'CONST' use64
assume cs:_eh_frame_hdr
;org 0D54h
__GNU_EH_FRAME_HDR db    1
db  1Bh
db    3
db  3Bh ; ;
db  50h ; P
db    0
db    0
db    0
db    9
db    0
db    0
db    0
db  1Ch
db 0F9h
db 0FFh
db 0FFh
db  9Ch
db    0
db    0
db    0
db  7Ch ; |
db 0F9h
db 0FFh
db 0FFh
db 0C4h
db    0
db    0
db    0
db  8Ch
db 0F9h
db 0FFh
db 0FFh
db  6Ch ; l
db    0
db    0
db    0
db 0BCh
db 0FAh
db 0FFh
db 0FFh
db 0DCh
db    0
db    0
db    0
db 0FEh
db 0FAh
db 0FFh
db 0FFh
db 0FCh
db    0
db    0
db    0
db  37h ; 7
db 0FBh
db 0FFh
db 0FFh
db  1Ch
db    1
db    0
db    0
db 0B7h
db 0FEh
db 0FFh
db 0FFh
db  44h ; D
db    1
db    0
db    0
db 0CCh
db 0FEh
db 0FFh
db 0FFh
db  64h ; d
db    1
db    0
db    0
db  3Ch ; <
db 0FFh
db 0FFh
db 0FFh
db 0ACh
db    1
db    0
db    0
_eh_frame_hdr ends


; Segment type: Pure data
; Segment permissions: Read
_eh_frame segment qword public 'CONST' use64
assume cs:_eh_frame
;org 0DA8h
db  14h
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    1
db  7Ah ; z
db  52h ; R
db    0
db    1
db  78h ; x
db  10h
db    1
db  1Bh
db  0Ch
db    7
db    8
db  90h
db    1
db    7
db  10h
db  14h
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db  18h
db 0F9h
db 0FFh
db 0FFh
db  2Bh ; +
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db  14h
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    1
db  7Ah ; z
db  52h ; R
db    0
db    1
db  78h ; x
db  10h
db    1
db  1Bh
db  0Ch
db    7
db    8
db  90h
db    1
db    0
db    0
db  24h ; $
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db  78h ; x
db 0F8h
db 0FFh
db 0FFh
db  60h ; `
db    0
db    0
db    0
db    0
db  0Eh
db  10h
db  46h ; F
db  0Eh
db  18h
db  4Ah ; J
db  0Fh
db  0Bh
db  77h ; w
db    8
db  80h
db    0
db  3Fh ; ?
db  1Ah
db  3Bh ; ;
db  2Ah ; *
db  33h ; 3
db  24h ; $
db  22h ; "
db    0
db    0
db    0
db    0
db  14h
db    0
db    0
db    0
db  44h ; D
db    0
db    0
db    0
db 0B0h
db 0F8h
db 0FFh
db 0FFh
db    8
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db  5Ch ; \
db    0
db    0
db    0
db 0D8h
db 0F9h
db 0FFh
db 0FFh
db  42h ; B
db    0
db    0
db    0
db    0
db  41h ; A
db  0Eh
db  10h
db  86h
db    2
db  43h ; C
db  0Dh
db    6
db  7Dh ; }
db  0Ch
db    7
db    8
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db  7Ch ; |
db    0
db    0
db    0
db 0FAh
db 0F9h
db 0FFh
db 0FFh
db  39h ; 9
db    0
db    0
db    0
db    0
db  41h ; A
db  0Eh
db  10h
db  86h
db    2
db  43h ; C
db  0Dh
db    6
db  74h ; t
db  0Ch
db    7
db    8
db    0
db    0
db    0
db  24h ; $
db    0
db    0
db    0
db  9Ch
db    0
db    0
db    0
db  13h
db 0FAh
db 0FFh
db 0FFh
db  80h
db    3
db    0
db    0
db    0
db  41h ; A
db  0Eh
db  10h
db  86h
db    2
db  43h ; C
db  0Dh
db    6
db  4Eh ; N
db  8Eh
db    3
db  8Dh
db    4
db  8Ch
db    5
db  83h
db    6
db    3
db  6Dh ; m
db    3
db  0Ch
db    7
db    8
db  1Ch
db    0
db    0
db    0
db 0C4h
db    0
db    0
db    0
db  6Bh ; k
db 0FDh
db 0FFh
db 0FFh
db  15h
db    0
db    0
db    0
db    0
db  41h ; A
db  0Eh
db  10h
db  86h
db    2
db  43h ; C
db  0Dh
db    6
db  50h ; P
db  0Ch
db    7
db    8
db    0
db    0
db    0
db  44h ; D
db    0
db    0
db    0
db 0E4h
db    0
db    0
db    0
db  60h ; `
db 0FDh
db 0FFh
db 0FFh
db  65h ; e
db    0
db    0
db    0
db    0
db  42h ; B
db  0Eh
db  10h
db  8Fh
db    2
db  42h ; B
db  0Eh
db  18h
db  8Eh
db    3
db  45h ; E
db  0Eh
db  20h
db  8Dh
db    4
db  42h ; B
db  0Eh
db  28h ; (
db  8Ch
db    5
db  48h ; H
db  0Eh
db  30h ; 0
db  86h
db    6
db  48h ; H
db  0Eh
db  38h ; 8
db  83h
db    7
db  4Dh ; M
db  0Eh
db  40h ; @
db  72h ; r
db  0Eh
db  38h ; 8
db  41h ; A
db  0Eh
db  30h ; 0
db  41h ; A
db  0Eh
db  28h ; (
db  42h ; B
db  0Eh
db  20h
db  42h ; B
db  0Eh
db  18h
db  42h ; B
db  0Eh
db  10h
db  42h ; B
db  0Eh
db    8
db    0
db  14h
db    0
db    0
db    0
db  2Ch ; ,
db    1
db    0
db    0
db  88h
db 0FDh
db 0FFh
db 0FFh
db    2
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
__FRAME_END__ db    0
db    0
db    0
db    0
_eh_frame ends

; ELF Initialization Function Table

; Segment type: Pure data
; Segment permissions: Read/Write
_init_array segment qword public 'DATA' use64
assume cs:_init_array
;org 201DD8h
__frame_dummy_init_array_entry dq offset frame_dummy ; Alternative name is '__init_array_start'
_init_array ends

; ELF Termination Function Table

; Segment type: Pure data
; Segment permissions: Read/Write
_fini_array segment qword public 'DATA' use64
assume cs:_fini_array
;org 201DE0h
__do_global_dtors_aux_fini_array_entry dq offset __do_global_dtors_aux ; Alternative name is '__init_array_end'
_fini_array ends


; Segment type: Pure data
; Segment permissions: Read/Write
_jcr segment qword public 'DATA' use64
assume cs:_jcr
;org 201DE8h
__JCR_LIST__ db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
_jcr ends

; ELF Dynamic Information

; Segment type: Pure data
; Segment permissions: Read/Write
LOAD segment byte public 'DATA' use64
assume cs:LOAD
;org 201DF0h
_DYNAMIC Elf64_Dyn <1, 1> ; DT_NEEDED libc.so.6
Elf64_Dyn <0Ch, 658h>   ; DT_INIT
Elf64_Dyn <0Dh, 0C94h>  ; DT_FINI
Elf64_Dyn <19h, 201DD8h> ; DT_INIT_ARRAY
Elf64_Dyn <1Bh, 8>      ; DT_INIT_ARRAYSZ
Elf64_Dyn <1Ah, 201DE0h> ; DT_FINI_ARRAY
Elf64_Dyn <1Ch, 8>      ; DT_FINI_ARRAYSZ
Elf64_Dyn <6FFFFEF5h, 298h> ; DT_GNU_HASH
Elf64_Dyn <5, 3F8h>     ; DT_STRTAB
Elf64_Dyn <6, 2C0h>     ; DT_SYMTAB
Elf64_Dyn <0Ah, 0B7h>   ; DT_STRSZ
Elf64_Dyn <0Bh, 18h>    ; DT_SYMENT
Elf64_Dyn <15h, 0>      ; DT_DEBUG
Elf64_Dyn <3, 202000h>  ; DT_PLTGOT
Elf64_Dyn <2, 78h>      ; DT_PLTRELSZ
Elf64_Dyn <14h, 7>      ; DT_PLTREL
Elf64_Dyn <17h, 5E0h>   ; DT_JMPREL
Elf64_Dyn <7, 4F0h>     ; DT_RELA
Elf64_Dyn <8, 0F0h>     ; DT_RELASZ
Elf64_Dyn <9, 18h>      ; DT_RELAENT
Elf64_Dyn <6FFFFFFBh, 8000000h> ; DT_FLAGS_1
Elf64_Dyn <6FFFFFFEh, 4D0h> ; DT_VERNEED
Elf64_Dyn <6FFFFFFFh, 1> ; DT_VERNEEDNUM
Elf64_Dyn <6FFFFFF0h, 4B0h> ; DT_VERSYM
Elf64_Dyn <6FFFFFF9h, 3> ; DT_RELACOUNT
Elf64_Dyn <0>           ; DT_NULL
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
LOAD ends


; Segment type: Pure data
; Segment permissions: Read/Write
_got segment qword public 'DATA' use64
assume cs:_got
;org 201FD0h
_ITM_deregisterTMCloneTable_ptr dq offset _ITM_deregisterTMCloneTable
__libc_start_main_ptr dq offset __libc_start_main
__gmon_start___ptr dq offset __gmon_start__
_Jv_RegisterClasses_ptr dq offset _Jv_RegisterClasses
_ITM_registerTMCloneTable_ptr dq offset _ITM_registerTMCloneTable
__cxa_finalize_ptr dq offset __imp___cxa_finalize
_got ends


; Segment type: Pure data
; Segment permissions: Read/Write
_got_plt segment qword public 'DATA' use64
assume cs:_got_plt
;org 202000h
_GLOBAL_OFFSET_TABLE_ dq offset _DYNAMIC
qword_202008 dq 0
qword_202010 dq 0
off_202018 dq offset puts
off_202020 dq offset strlen
off_202028 dq offset fgets
off_202030 dq offset strcmp
off_202038 dq offset ptrace
_got_plt ends


; Segment type: Pure data
; Segment permissions: Read/Write
_data segment qword public 'DATA' use64
assume cs:_data
;org 202040h
public __data_start ; weak
__data_start db    0    ; Alternative name is '__data_start'
                        ; data_start
db    0
db    0
db    0
db    0
db    0
db    0
db    0
public __dso_handle
; void *_dso_handle
__dso_handle dq offset __dso_handle
_data ends


; Segment type: Uninitialized
; Segment permissions: Read/Write
_bss segment para public 'BSS' use64
assume cs:_bss
;org 202050h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
public __bss_start
; FILE *_bss_start
__bss_start dq ?        ; Alternative name is '__TMC_END__'
                        ; stdin@@GLIBC_2.2.5
                        ; _edata
                        ; Copy of shared data
completed_6972 db ?
align 20h
_bss ends


; Segment type: Zero-length
_prgend segment byte public '' use64
_end label byte
_prgend ends


; Segment type: Externs
; extern
; int puts(const char *s)
extrn puts:near
; size_t strlen(const char *s)
extrn strlen:near
; int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end)
extrn __libc_start_main:near
; char *fgets(char *s, int n, FILE *stream)
extrn fgets:near
; int strcmp(const char *s1, const char *s2)
extrn strcmp:near
; __int64 ptrace(enum __ptrace_request request, ...)
extrn ptrace:near
; int __cxa_finalize(void *)
extrn __imp___cxa_finalize:near ; weak
extrn _ITM_deregisterTMCloneTable ; weak
extrn __gmon_start__:near ; weak
extrn _Jv_RegisterClasses:near ; weak
extrn _ITM_registerTMCloneTable ; weak


end _start
